# Copyright 2024 Bloomberg Finance L.P.
# Distributed under the terms of the MIT license.

import os
import re
import common
import tempfile
from pathlib import Path
from typing import Optional
from function_data import FunctionData
from spec import Postcondition

class DaikonGenerator:
    """
    An invariant generator tool based on dynamic analyis https://plse.cs.washington.edu/daikon
    """
    def __init__(self) -> None:
        # Check if Daikon is installed correctly
        daikon_dir = os.getenv('DAIKONDIR')
        self.daikon_path = Path(daikon_dir + '/daikon.jar')

        if not self.daikon_path.is_file():
            raise ValueError('Cannot find Daikon. Make sure that Daikon is installed environment variable `DAIKONDIR` is set.')
        

    def get_postcondition(self, fn_data:FunctionData) -> Optional[Postcondition]:
        """
        Returns a postocondition string generated by Daikon.
        """
        #  g++ -gdwarf-2 -no-pie  example.cpp -o example.o
        with tempfile.NamedTemporaryFile(suffix='.o', delete=True) as f:
            print('Function:\n', fn_data.function_string)

            compile_cmd = f"g++ -gdwarf-2 -no-pie  {fn_data.file_path} -o {f.name}"
            o1 = common.run_bash(compile_cmd)
            
            if o1 is None or o1.returncode == 1:
                print(f'The command "{compile_cmd}" failed! Make sure the provided source code compiles.')
                return None, None

            # kvasir-dtrace ./example.o
            # TODO: Check that kvasir-dtrace is installed?
            fname = f.name.split('/')[-1]
            dtrace_file = f"daikon-output/{fname}.dtrace"
            decl_file = f"daikon-output/{fname}.decls"
            inv_file = f"daikon-output/{fname}.inv"

            trace_cmd = f"kvasir-dtrace --ignore-globals {f.name}"
            o2 = common.run_bash(trace_cmd)
            if o2 is None or o2.returncode == 1:
                raise ValueError(f'The command "{trace_cmd}" failed! Make sure kvasir-dtrace frontend for daikon is installed.')

            #  Run Daikon analysis:
            #  java -cp $DAIKONDIR/daikon.jar daikon.Daikon \
            #      --config_option daikon.derive.Derivation.disable_derived_variables=true \
            #      daikon-output/example.o.dtrace daikon-output/example.o.decls
            daikon_run_cmd = f"java -cp {self.daikon_path} daikon.Daikon \
            --config_option daikon.derive.Derivation.disable_derived_variables=true \
            {dtrace_file} {decl_file} --format Java -o {inv_file}"
            o3 = common.run_bash(daikon_run_cmd)

            # The output is in Java format
            # See other formats here: https://plse.cs.washington.edu/daikon/download/doc/daikon.html#Invariant-syntax
            if o3 is None or o3.returncode == 1:
                print(f'The command "{daikon_run_cmd}" failed! Make sure daikon is installed.')
                return None, None
            
            # Extract the postcondition from the generated invariants
            # post = re.search(f'{fn_data.function_name}(.*)EXIT\n(.*)\n((.|\n)*)(Exiting.*|^=====)', o3.stdout.decode('utf-8')).group(3)
            post = None
            lines = o3.stdout.decode('utf-8').split('\n')
            for i, line in enumerate(lines):
                if 'EXIT' in line and fn_data.function_name in line:
                    j = i+1
                    while j < len(lines):
                        if 'return' in lines[j] and '\\' not in lines[j]:                    
                            post = lines[j]
                            post = post.rstrip('\n').split('\n')[0].replace('return', 'res_tmp')
                            break
                        elif '=====' in lines[j]:
                            break
                        j += 1
            
            return Postcondition(predicate=post, reasoning=None, prob=0), None
