# Copyright 2024 Bloomberg Finance L.P.
# Distributed under the terms of the MIT license.

import ast
from collections import defaultdict
from github import Github, InputGitTreeElement
import github
import requests
import sys, os
sys.path.append(os.path.join(os.path.dirname(__file__), '..', 'fun2spec'))
import common


# GitHub settings
GITHUB_TOKEN = os.environ['GITHUB_TOKEN'] # Set this environment variable
REPO_OWNER = os.environ.get('GITHUB_REPO_OWNER', 'bloomberg')  # Override with GITHUB_REPO_OWNER env var
REPO_NAME = os.environ.get('GITHUB_REPO_NAME', 'bde')  # Override with GITHUB_REPO_NAME env var

# Verify repository exists
response = requests.get(f'https://api.github.com/repos/{REPO_OWNER}/{REPO_NAME}', verify=False)
NEW_BRANCH_NAME = 'auto_contracts'
BASE_BRANCH_NAME = 'main'  # or the branch you want to base your PR on
COMMIT_MESSAGE = 'Added contract comments'
PR_TITLE = 'Automatic specifications'
PR_BODY = 'This is autogenerated specifications for the given function'

# Authenticate with GitHub
g = Github(GITHUB_TOKEN, verify=False)

# Get the repository
repo = g.get_repo(f"{REPO_OWNER}/{REPO_NAME}")

# Create a new branch
def create_branch():
    base_branch = repo.get_branch(BASE_BRANCH_NAME)
    ref_name = f"refs/heads/{NEW_BRANCH_NAME}"

    try:
        repo.get_git_ref(f"heads/{NEW_BRANCH_NAME}")
        print(f"Ref {ref_name} exists.")
    except Exception as e:
        print(e)
        repo.create_git_ref(ref=ref_name, sha=base_branch.commit.sha)
    
    print(f"Branch '{NEW_BRANCH_NAME}' created.")

def edit_files():
    model_name = "Qwen/Qwen2.5-32B-Instruct"
    count = 2000 
    return_type = 'all'
    gen_name = 'fun2spec'
    source = 'bde'

    # Load the json file with results
    log_path = f"{common.get_project_path()}/data/{common.get_source_name(source)}/{model_name}/"
    log_file_name = f"gen_name:{gen_name}_return_type:{return_type}_count:{count}"
    log_res_path = f"{log_path}/{log_file_name}.jsonl"

    # Store changes in a list
    file_lines = common.get_file_lines(log_res_path)

    # Store changes by file
    changes = defaultdict(list)

    for line in file_lines:
        data_dict = ast.literal_eval(line)

        if 'result' not in data_dict or not data_dict['result']: # Fail on a test
            continue
        
        clean_post = data_dict['postcondition'].replace(' ', '')
        if  clean_post in ['true', 'res_tmp!=NULL||res_tmp==NULL', 'res_tmp==NULL||res_tmp!=NULL', 'res_tmp==0||res_tmp!=0', 'res_tmp==0||res_tmp!=0', 'res_tmp==true||res_tmp==false', 'res_tmp==false||res_tmp==true']:
            continue
        
        # Get the file content
        # Extract relative path by splitting on the repo name
        file_path = data_dict['file'].split(f'{REPO_NAME}/')[1]
        file_content = repo.get_contents(file_path, ref=BASE_BRANCH_NAME)

        # Read the file content as a string
        original_content = file_content.decoded_content.decode()

        # Calculate the offset in bytes
        offset = data_dict['offset']
        postcondition_line = data_dict['postcondition'].replace('res_tmp', '__out') + "\n"

        # Store the change with the offset
        changes[file_path].append((offset, postcondition_line))

    # Get the current commit and the existing tree
    base_branch = repo.get_branch(BASE_BRANCH_NAME)
    current_commit = base_branch.commit
    existing_tree = current_commit.commit.tree

    # Prepare the tree elements for the new commit
    tree_elements = []

    for file_path, edits in changes.items():
        # Get the latest file content for this specific file
        file_content = repo.get_contents(file_path, ref=BASE_BRANCH_NAME)
        original_content = file_content.decoded_content.decode()

        # Sort edits by offset
        edits.sort(key=lambda x: x[0])

        # Create new content with all changes applied
        new_content = original_content
        offset_adjustment = 0

        for offset, line in edits:
            # Adjust the offset based on previous insertions
            adjusted_offset = offset + offset_adjustment
            new_content = new_content[:adjusted_offset] + line + new_content[adjusted_offset:]
            offset_adjustment += len(line)

        # Create a new InputGitTreeElement for each modified file
        tree_element = InputGitTreeElement(path=file_path, mode='100644', type='blob', content=new_content)
        tree_elements.append(tree_element)

    # Create the new tree
    new_tree = repo.create_git_tree(tree_elements, base_tree=existing_tree)

    # Get the current commit to create a new one based on it
    # Use the BASE_BRANCH_NAME to get the latest commit on that branch
    base_branch = repo.get_branch(BASE_BRANCH_NAME)
    current_commit = base_branch.commit.commit  # Get the latest commit from the branch

    # Create a new commit
    new_commit = repo.create_git_commit(
        message=COMMIT_MESSAGE,
        tree=new_tree,
        parents=[current_commit]
    )

    # Update the reference to the new commit
    repo.get_git_ref(f'heads/{NEW_BRANCH_NAME}').edit(new_commit.sha, force=True)

# Create a pull request
def create_pull_request():
    try:
        pr = repo.create_pull(title=PR_TITLE, body=PR_BODY, head=NEW_BRANCH_NAME, base=BASE_BRANCH_NAME)
        print(f"Pull request created: {pr.html_url}")
    except github.GithubException as e:
        print('The PR already exists. This is fine. The existing PR should be updated.')

# Main execution
if __name__ == "__main__":
    create_branch()
    edit_files()
    create_pull_request()
    